name: Monitor Repositories

on:
  push:
    branches:
      - master

jobs:
  monitor-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Determine which repository triggered the webhook
      run: echo $GITHUB_REPOSITORY
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests with Maven
      run: mvn test
    # Perform the desired actions based on the repository that triggered the webhook
